name: ronpa
description: Ronpa Dart implementation
version: 1.0.0
homepage: https://github.com/SudoDotDog/Ronpa-Dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  numeric: ^1.0.2

dev_dependencies:
  test: ^1.12.0
