name: ronpa
description: Ronpa Dart implementation
version: 0.0.1
homepage: https://github.com/SudoDotDog/Ronpa-Dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  numeric: ^1.0.1

dev_dependencies:
  test: ^1.12.0
