name: ronpa
description: Ronpa Dart implementation
version: 0.0.1
homepage: https://sudo.dog

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  numeric:
    path: ../Dart-Numeric

dev_dependencies:
  test: ^1.12.0
